### PR TITLE
Added option to provide an existing mqtt client for the connection.

### PR DESCRIPTION
**Pull request by vschroeter**
**Table of Contents**  *generated with [DocToc](https://github.com/thlorenz/doctoc)*

- [Description](#description)
- [License Acceptance](#license-acceptance)
- [Type of changes](#type-of-changes)
- [Checklist](#checklist)

# Description

Added the option to provide an existing mqtt client for the connection.
This can be used for the following use cases:
- Using the library in an application, where there is already an MQTT client created / managed by other parts of the program or other libraries. Especially when the credentials for a connection are externally managed and not easily available to pass to the `Settings.MQTT` option, this is useful.
- Offering compatibility with `paho-mqtt` version >2.0.0, where the client instantiation has changed. By providing an existing client, the library does not need to instantiate an own client and thus does not run into deprecation problems.

The existing mqtt client can be passed to th `Settings.MQTT` object as following:
```py
from ha_mqtt_discoverable import Settings
from paho.mqtt.client import Client

# Creating the MQTT client
client = Client()
# Doing other stuff with the client, like connecting to the broker
# ...

# Providing the client to the Settings object
# In this case, no other MQTT settings are needed
mqtt_settings = Settings.MQTT(client=client)

# Continue with the rest of the code as usual
``` 

# License Acceptance

- [x] This repository is Apache version 2.0 licensed and by making this PR, I am contributing my changes to the repository under the terms of the Apache 2 license.

# Type of changes

- [ ] Add/update a helper script
- [ ] Add/update link to an external resource like a blog post or video
- [ ] Bug fix
- [x] New feature
- [ ] Test updates
- [ ] Text cleanups/updates

# Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/unixorn/ha-mqtt-discovery/blob/main/Contributing.md) document.
- [x] All new and existing tests pass.
- [x] I have confirmed that any links added or updated in my PR are valid.

### CODE REVIEW

**Review by unixorn — APPROVED** [review]
LGTM, thanks for the contribution!

**Comment by unixorn** [comment]
Will do a release with this by the end of this weekend.

**Comment by vschroeter** [comment]
Thank you for the fast response and thanks for the project!

**Comment by unixorn** [comment]
Included in v0.16, thank you!

**Pull request merged**
