### PR TITLE
added missing last_reset to sensor for metering (electricity,gas, water etc.)

### PR DESCRIPTION
**Pull request by unl0ck**
**Table of Contents**  *generated with [DocToc](https://github.com/thlorenz/doctoc)*

- [Description](#description)
- [License Acceptance](#license-acceptance)
- [Type of changes](#type-of-changes)
- [Checklist](#checklist)

# Description

Sensors has an optional attribute last_reset read 
https://developers.home-assistant.io/docs/core/entity/sensor/#properties

# License Acceptance

- [x] This repository is Apache version 2.0 licensed and by making this PR, I am contributing my changes to the repository under the terms of the Apache 2 license.

# Type of changes

- [ ] Add/update a helper script
- [ ] Add/update link to an external resource like a blog post or video
- [x] Bug fix
- [ ] New feature
- [ ] Test updates
- [ ] Text cleanups/updates

# Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/unixorn/ha-mqtt-discovery/blob/main/Contributing.md) document.
- [ ] All new and existing tests pass.
- [ ] Any scripts added use `#!/usr/bin/env interpreter` instead of potentially platform-specific direct paths (`#!/bin/sh` is an allowed exception)
- [ ] Scripts added/updated in this PR are all marked executable.
- [ ] Scripts added/updated in this PR _do not_ have a language file extension unless they are meant to be sourced and not run standalone. No one should have to know if a script was written in bash, python, ruby or whatever. Not including file extensions makes it easier to rewrite the script in another language later without having to change every reference to the previous version.
- [ ] I have confirmed that any links added or updated in my PR are valid.

### CODE REVIEW

**Comment by unl0ck** [comment]
@unixorn could you check please whats wrong?

**Review by unixorn — APPROVED** [review]
Thanks for the help! I'll push a new version this afternoon.

**Comment by unl0ck** [comment]
Nice perfect and thank you @unixorn

**Comment by unl0ck** [comment]
@unixorn I dont want make pressure, but for my addon I need this change, to continue my work 😅

**Comment by unixorn** [comment]
Sorry about the delay, been a busy week at work. It's pushed to pypi now as [0.16.2](https://github.com/unixorn/ha-mqtt-discoverable/releases/tag/v0.16.2).

**Comment by unixorn** [comment]
When your addon is complete, please PR in a link to it in the readme. What does your addon do?

**Comment by unl0ck** [comment]
read the measurments from viessmann gridbox the PV and battery

**Pull request merged**
