### PR TITLE
Added select, image and camera entities

### LINKED ISSUE #109: REQUEST for camera entities
**Is your feature request related to a problem? Please describe.**
Hi , it it possible to create also support for camera entities, to upload maybe jpg pictures files?

thnx in advance

### PR DESCRIPTION
**Pull request by Gifford47**
**Table of Contents**  *generated with [DocToc](https://github.com/thlorenz/doctoc)*

- [Description](#description)
- [License Acceptance](#license-acceptance)
- [Type of changes](#type-of-changes)
- [Checklist](#checklist)

# Description

Closes #109

# License Acceptance

- [x] This repository is Apache version 2.0 licensed and by making this PR, I am contributing my changes to the repository under the terms of the Apache 2 license.

# Type of changes

- [x] Add/update a helper script
- [ ] Add/update link to an external resource like a blog post or video
- [ ] Bug fix
- [x] New feature
- [ ] Test updates
- [x] Text cleanups/updates

# Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/unixorn/ha-mqtt-discovery/blob/main/Contributing.md) document.
- [] All new and existing tests pass.
- [ ] Any scripts added use `#!/usr/bin/env interpreter` instead of potentially platform-specific direct paths (`#!/bin/sh` is an allowed exception)
- [ ] Scripts added/updated in this PR are all marked executable.
- [ ] Scripts added/updated in this PR _do not_ have a language file extension unless they are meant to be sourced and not run standalone. No one should have to know if a script was written in bash, python, ruby or whatever. Not including file extensions makes it easier to rewrite the script in another language later without having to change every reference to the previous version.
- [x] I have confirmed that any links added or updated in my PR are valid.

### CODE REVIEW

**Comment by Gifford47** [comment]
Thanks for this awesome lib! I've added camera, image and selection discovery. It's tested manually on my host machine, so I've not added any tests to this repo yet. Do you merge it also without the tests?

**Review by unixorn — APPROVED** [review]
lgtm!

**Comment by unixorn** [comment]
Included in v0.16, thank you!

**Comment by Gifford47** [comment]
There a mistake in the readme for the selection entity.
Current: my_selection.set_options()
Corrected: my_selection.set_options(opt)

Could you fix that next time when touching readme?

**Pull request merged**
